<!DOCTYPE html>
<html lang="es_CL">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>COLMESOFT :: Login</title>
<link rel="stylesheet" href="/css/siimple/siimple.min.css" />
</head>
<body>

<!-- SCRIPTS -->
<script type="text/javascript" src="/js/login.js"></script>
<!-- SCRIPTS -->
</body>
</html>