<!DOCTYPE html>
<html lang="es_CL">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>COLMESOFT :: <?=$this->e($titulo)?></title>
<link rel="stylesheet" href="/css/bulma.min.css" />
</head>
<body>
<div class="container is-fluid">
<?=$this->section('content')?>
</div>

<!-- SCRIPTS -->
<script type="text/javascript" src="/js/scripts.js"></script>
<!-- SCRIPTS -->
</body>
</html>